---
title: "Ten simple rules for building Master’s of Data Science program"
author: 
- Tiffany A. Timbers
- Michael A. Gelbart

date: "`r Sys.Date()`"
documentclass: paper
bibliography: [references.bib]
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, ft.align = "left")
library(knitr)
```

## Abstract
The University of British Columba (UBC) Master of Data Science (MDS) program 
is a 10-month professional master’s program in Data Science. 
The MDS program was launched in September 2016 and is offered 
by a collaboration between the UBC Department of Computer Science 
and Department of Statistics.
It involves 24 one-month courses followed by a two-month Capstone Project. 
It has grown from 22 students with just under 100 applicants at its onset, 
to 120 students with over 2000 applicants in its most recent application cycle. 
In this article we document some of the things 
we think have been key to the success of building this successful program.

## Introduction
- describe program and its history (pull from blog)
- document its measurable success
  - student body growth
  - admissions applications growth
  - spin-off programs at UBC (MDS-O, MDS-CL)
- document some testimonials
  - can we get these from the marketing team?

## Ten simple rules
- we will flesh these out in the sprint

### Rule 1: Engage (at least) statisticians and computer scientists - Think broadly about the definition of data science & Feed students their vegetables

### Rule 2: teach current/authentic data science concepts, methods and tools & build courses from scratch & use real data sets

### Rule 3: create a teaching team that is connected to each other and the entire curriculum & break down the walls between courses

### Rule 4: reflect and iterate (time for redevelopment, academic retreats, not being scared of paperwork, capstone)

### Rule 5: use evidence-based pedagogies for learning data science (live coding, flipped classroom, experiential learning)

### Rule 6: use (and create?) open educational resources

### Rule 7: Include meaningful group projects (group + projects = do together)

### Rule 8: Scaffold a respectful and supportive community for learners 

Having a respectful and supportive community 
for learners is fundamental for leveling the playing field 
across a group of heterogeneous learners - 
which is essentially any group of learners.
Learner heterogeneity may be particularly higher in a Master of Data Science 
program given that students come from a wide variety of academic backgrounds.
In a classroom where a respectful and supportive community is not built, 
only some learners who have certain privileges are likely to succeed. 
In such an unsafe environment, 
many learners lacking these certain privileges will become demotivated, 
frustrated, and feel alone. 
Their learning will suffer because of this, 
no matter how well the content is delivered by the teaching team. 

One way to scaffold a respectful and supportive community 
is to use and enforce a code of conduct 
that clearly outlines what behaviors are not acceptable in our learning spaces, 
and a process for reporting a code of conduct violation. 
Importantly, providing contact details for a secondary reporting person is 
important, in case the person listed I as the reporting person
(unintentionally) violate the code of conduct. 
- how we enforce the code of conduct - publicly but respectfully

Other ways we do this in MDS:
- careful choice of data sets (e.g., not using iris, calling out limitations
on how data has been collected - sex and gender are not binary, using diverse 
data sets that diverse people can identify with)
- learn students names
- announce when we make mistakes, **show our human-side**

- D&I workshops/Ally skills workshops - professional training

- team work document

### Rule 9: Spend time with the students (contact hours, student-teacher ratios) 

### Rule 10: Engage your alumni

Every year we marvel at how amazing our students are. We’re always sad to see them go in July, but they aren’t actually gone - they are now MDS alumni! Our alumni are engaged with the program in a variety of ways. All alumni (including faculty/staff alumni) are members of the UBC MDS Alumni Slack, where people post jobs ads, ask/answer data science questions, and just generally stay in touch. Beyond that, our alumni generously volunteer their time to give talks to current students (e.g. at orientation, or at an employer seminar or Capstone seminar), to participate in career-building events (e.g. conducting mock interviews with current students), to pair up with a current students as part of our mentorship program, or to partner with us for Capstone projects (it’s always a delight to have MDS alumni on the other side of the table). Keeping alumni engaged with the program has benefits for both current students and alumni. Current students receive mentorship, wisdom, and employment opportunities. Alumni have an avenue to stay up-to-date on data science techniques, partner on Capstone projects, and hopefully hire some great data scientists. It’s a big win for everyone.

## Conclusion
- TBD

## References
