---
title: "Ten simple rules for building Master’s of Data Science program"
author: 
- Tiffany A. Timbers
- Michael A. Gelbart
date: Sys.Date()
bibliography: references.bib
format: 
  pdf:
    toc: false
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, ft.align = "left")
library(knitr)
```

## Abstract
The University of British Columba (UBC) Master of Data Science (MDS) program 
is a 10-month professional master’s program in Data Science. 
The MDS program was launched in September 2016 and is offered 
by a collaboration between the UBC Department of Computer Science 
and Department of Statistics.
It involves 24 one-month courses followed by a two-month Capstone Project. 
It has grown from 22 students with just under 100 applicants at its onset, 
to 120 students with over 2000 applicants in its most recent application cycle. 
In this article we document some of the things 
we think have been key to the success of building this successful program.

## Introduction
- describe program and its history (pull from blog)
- document its measurable success
  - student body growth
  - admissions applications growth
  - spin-off programs at UBC (MDS-O, MDS-CL)
- document some testimonials
  - can we get these from the marketing team?

## Ten simple rules

### Rule 1: Engage (at least) statisticians and computer scientists - Think broadly about the definition of data science & Feed students their vegetables

{{< include _01_breadth_vegetables.qmd >}}

### Rule 2: teach current data science concepts, methods and tools

{{< include _02_be_real_stay_current.qmd >}}

### Rule 3: create a teaching team that is connected to each other and the entire curriculum & break down the walls between courses

{{< include _03_teaching_team_walls.qmd >}}

### Rule 4: reflect and iterate (time for redevelopment, academic retreats, not being scared of paperwork, capstone)

{{< include _04_reflect_iterate.qmd >}}

### Rule 5: use evidence-based pedagogies for learning data science (live coding, flipped classroom, experiential learning)

{{< include _05_evidence_based_pedagogies.qmd >}}

### Rule 6: use (and create?) open educational resources

{{< include _06_oers.qmd >}}

### Rule 7: Include meaningful group projects (group + projects = do together)

{{< include _07_group_projects.qmd >}}

### Rule 8: Scaffold a respectful and supportive community for learners 

{{< include _08_community.qmd >}}

### Rule 9: Spend time with the students (contact hours, student-teacher ratios) 

{{< include _09_spend_time.qmd >}}

### Rule 10: Engage your alumni

{{< include _10_alumni.qmd >}}

## Conclusion
- TBD

## References
